name: Test if the build is not failing

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install
      - run: npm run build
